Updated cloud_tops.logic
minishmaker/rando-logic pull request #150
Opened 2021-04-04 15:44 UTC by Nimbus125

2021-04-21 12:24 UTC, CandyCrystal requested changes
The Zeffa Fluteaways needs to be entrances, and the crest needs do be an exit!

2021-04-21 13:04 UTC, Ibot02 requested changes

2021-04-21 13:04 UTC, Ibot02 commented on cloud_tops.logic
> +    BottomCenterRightPlatform -> SmallHole: item MoleMitts
You can also not jump into the hole and go across directly
```suggestion
    BottomCenterRightPlatform -> SmallHole: item MoleMitts
    BottomCenterRightPlatform -> BottomRightCornerPlatform: (item MoleMitts & item Cape)
```

2021-04-21 13:04 UTC, Ibot02 commented on cloud_tops.logic
> +    StartingPlatform -> BottomRightCornerPlatform: item MoleMitts
This tornado isn't close enough, so you also need cape
```suggestion
    StartingPlatform -> BottomRightCornerPlatform: (item MoleMitts & item Cape)
```

2021-04-22 07:19 UTC, CandyCrystal approved these changes
Looks good to me!

2021-04-25 13:17 UTC, Ibot02 commented on cloud_tops.logic
>      #Reusing the current name for CT Kinstones
No, you're not :P
```suggestion
```

2021-04-25 22:36 UTC, Ibot02 approved these changes

2024-06-02 14:23 UTC, merged