Stubs 4
minishmaker/rando-logic pull request #52
Opened 2021-04-01 13:15 UTC by CandyCrystal

I believe this should be the rest of the stubs all done!

2021-04-01 16:13 UTC, CandyCrystal commented
That should be it all fixed!

2021-04-01 17:26 UTC, Ibot02 commented on palace_of_winds.logic
> +  room GFCapeMiniboss
I think I'd prefer a name not based on vanilla placements where possible.
```suggestion
  room GFWizrobesMiniboss
```

2021-04-01 17:26 UTC, Ibot02 commented on town_minish_houses.logic
> +area TowninishHouses:
Probably a typo?
```suggestion
area TownMinishHouses:
```

2021-04-01 17:26 UTC, Ibot02 commented on well.logic
> +  room WellEntry
I think
```suggestion
  room SouthEntry
```
is clearer?

2021-04-01 17:48 UTC, Ibot02 approved these changes

2021-04-03 13:31 UTC, Ibot02 requested changes

2021-04-03 13:31 UTC, Ibot02 commented on castle_courtyard.logic
> +  room Main
Isn't this already included? In hyrule_castle_garden.logic

2021-04-03 21:52 UTC, merged